model: xception
input_size: 299
batch_size: 32
epochs: 10
learning_rate: 0.0001
experiment_name: default_experiment
tracking_uri: file:./mlruns
seed: 42
train_data_dir: data/processed/train
val_data_dir: data/processed/val
checkpoint_dir: models/
