model: xception
input_size: 299

batch_size: 64
epochs: 6
learning_rate: 0.0001

num_workers: 12
class_weighted_loss: true

experiment_name: hufs_cluster_xception_bs64_e6
tracking_uri: file:./mlruns

seed: 42

train_data_dir: /mnt/ssd/deeperforensics/frames/train
val_data_dir: /mnt/ssd/deeperforensics/frames/val
test_data_dir: /mnt/ssd/deeperforensics/frames/test

checkpoint_dir: /mnt/ssd/project/outputs/checkpoints
